package Formularios;

import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class ProyectosVAN extends javax.swing.JFrame {
    public String Nombre1[];
    public double Costoi[];
    public double Costoa[];
    public double Valors[];
    public double Vidau[];
    
    public ProyectosVAN(String nombre[], double ci[], double ca[], double vs[], double vid[]) {
        initComponents();
        btnReg.setOpaque(false);
        btnReg.setContentAreaFilled(false);
        btnReg.setBorderPainted(false);
        
        Nombre1 = nombre[];
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlnm5 = new javax.swing.JLabel();
        jlnm4 = new javax.swing.JLabel();
        jlnm1 = new javax.swing.JLabel();
        jlnm2 = new javax.swing.JLabel();
        jlnm3 = new javax.swing.JLabel();
        jlci5 = new javax.swing.JLabel();
        jlci2 = new javax.swing.JLabel();
        jlci4 = new javax.swing.JLabel();
        jlci3 = new javax.swing.JLabel();
        jlci1 = new javax.swing.JLabel();
        ca2 = new javax.swing.JLabel();
        ca5 = new javax.swing.JLabel();
        ca1 = new javax.swing.JLabel();
        ca3 = new javax.swing.JLabel();
        ca4 = new javax.swing.JLabel();
        vs5 = new javax.swing.JLabel();
        vs3 = new javax.swing.JLabel();
        vs4 = new javax.swing.JLabel();
        vs2 = new javax.swing.JLabel();
        vd4 = new javax.swing.JLabel();
        vd5 = new javax.swing.JLabel();
        vd3 = new javax.swing.JLabel();
        vs1 = new javax.swing.JLabel();
        vd2 = new javax.swing.JLabel();
        vd1 = new javax.swing.JLabel();
        jlnm6 = new javax.swing.JLabel();
        jlnm7 = new javax.swing.JLabel();
        jlnm8 = new javax.swing.JLabel();
        jlnm9 = new javax.swing.JLabel();
        jlnm10 = new javax.swing.JLabel();
        resp1 = new javax.swing.JLabel();
        resp2 = new javax.swing.JLabel();
        resp3 = new javax.swing.JLabel();
        resp4 = new javax.swing.JLabel();
        resp5 = new javax.swing.JLabel();
        mejor = new javax.swing.JLabel();
        btnReg = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(580, 370));
        setMinimumSize(new java.awt.Dimension(580, 370));
        setPreferredSize(new java.awt.Dimension(580, 370));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Vida:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 180, 80, 30);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 90, 30);

        jLabel3.setText("Costo Inicial:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 90, 90, 30);

        jLabel4.setText("Costo Anual:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 120, 90, 30);

        jLabel5.setText("Valor Salvamento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 150, 90, 30);

        jlnm5.setText("nm1");
        getContentPane().add(jlnm5);
        jlnm5.setBounds(400, 70, 70, 14);

        jlnm4.setText("nm1");
        getContentPane().add(jlnm4);
        jlnm4.setBounds(350, 70, 70, 14);

        jlnm1.setText("nm1");
        getContentPane().add(jlnm1);
        jlnm1.setBounds(150, 70, 70, 14);

        jlnm2.setText("nm1");
        getContentPane().add(jlnm2);
        jlnm2.setBounds(220, 70, 70, 14);

        jlnm3.setText("nm1");
        getContentPane().add(jlnm3);
        jlnm3.setBounds(290, 70, 70, 14);

        jlci5.setText("ci1");
        getContentPane().add(jlci5);
        jlci5.setBounds(400, 100, 60, 14);

        jlci2.setText("ci1");
        getContentPane().add(jlci2);
        jlci2.setBounds(220, 100, 60, 14);

        jlci4.setText("ci1");
        getContentPane().add(jlci4);
        jlci4.setBounds(350, 100, 60, 14);

        jlci3.setText("ci1");
        getContentPane().add(jlci3);
        jlci3.setBounds(290, 100, 60, 14);

        jlci1.setText("ci1");
        getContentPane().add(jlci1);
        jlci1.setBounds(150, 100, 60, 14);

        ca2.setText("ca1");
        getContentPane().add(ca2);
        ca2.setBounds(220, 130, 30, 14);

        ca5.setText("ca1");
        getContentPane().add(ca5);
        ca5.setBounds(400, 130, 30, 14);

        ca1.setText("ca1");
        getContentPane().add(ca1);
        ca1.setBounds(150, 130, 30, 14);

        ca3.setText("ca1");
        getContentPane().add(ca3);
        ca3.setBounds(290, 130, 30, 14);

        ca4.setText("ca1");
        getContentPane().add(ca4);
        ca4.setBounds(350, 130, 30, 14);

        vs5.setText("vs1");
        getContentPane().add(vs5);
        vs5.setBounds(400, 160, 30, 14);

        vs3.setText("vs1");
        getContentPane().add(vs3);
        vs3.setBounds(290, 160, 30, 14);

        vs4.setText("vs1");
        getContentPane().add(vs4);
        vs4.setBounds(350, 160, 30, 14);

        vs2.setText("vs1");
        getContentPane().add(vs2);
        vs2.setBounds(220, 160, 30, 14);

        vd4.setText("vd1");
        getContentPane().add(vd4);
        vd4.setBounds(350, 190, 30, 14);

        vd5.setText("vd1");
        getContentPane().add(vd5);
        vd5.setBounds(400, 190, 30, 14);

        vd3.setText("vd1");
        getContentPane().add(vd3);
        vd3.setBounds(290, 190, 30, 14);

        vs1.setText("vs1");
        getContentPane().add(vs1);
        vs1.setBounds(150, 160, 30, 14);

        vd2.setText("vd1");
        getContentPane().add(vd2);
        vd2.setBounds(220, 190, 30, 14);

        vd1.setText("vd1");
        getContentPane().add(vd1);
        vd1.setBounds(150, 190, 30, 14);

        jlnm6.setText("nm1");
        getContentPane().add(jlnm6);
        jlnm6.setBounds(200, 220, 50, 20);

        jlnm7.setText("nm1");
        getContentPane().add(jlnm7);
        jlnm7.setBounds(200, 240, 50, 20);

        jlnm8.setText("nm1");
        getContentPane().add(jlnm8);
        jlnm8.setBounds(200, 260, 50, 20);

        jlnm9.setText("nm1");
        getContentPane().add(jlnm9);
        jlnm9.setBounds(200, 280, 50, 20);

        jlnm10.setText("nm1");
        getContentPane().add(jlnm10);
        jlnm10.setBounds(200, 300, 50, 20);

        resp1.setText("Respuesta1");
        getContentPane().add(resp1);
        resp1.setBounds(300, 300, 110, 20);

        resp2.setText("Respuesta1");
        getContentPane().add(resp2);
        resp2.setBounds(300, 220, 110, 20);

        resp3.setText("Respuesta1");
        getContentPane().add(resp3);
        resp3.setBounds(300, 240, 110, 20);

        resp4.setText("Respuesta1");
        getContentPane().add(resp4);
        resp4.setBounds(300, 260, 110, 20);

        resp5.setText("Respuesta1");
        getContentPane().add(resp5);
        resp5.setBounds(300, 280, 110, 20);

        mejor.setText("Mejor");
        getContentPane().add(mejor);
        mejor.setBounds(460, 250, 50, 30);

        btnReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon1.png"))); // NOI18N
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        getContentPane().add(btnReg);
        btnReg.setBounds(510, 290, 50, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo14.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 580, 351);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        int eve = (new DatosGraficar().getValor5());
        int cont=0;
        
        JOptionPane.showInputDialog(eve);
        if(eve == 1)
        {
        jlnm1.setText(new DatosGraficar().getNombre());
        jlci1.setText(Double.toString(new DatosGraficar().getValor1()));
        ca1.setText(Double.toString(new DatosGraficar().getValor2()));
        vs1.setText(Double.toString(new DatosGraficar().getValor3()));
        vd1.setText(Double.toString(new DatosGraficar().getValor4()));
        }
              
        if(eve == 2)
        {
            cont = 1;
            for (int j=1; j<=2; j++)
                {
                if (cont == 1)
                        {
                        jlnm1.setText(new DatosGraficar().getNombre());
                        jlci1.setText(Double.toString(new DatosGraficar().getValor1()));
                        ca1.setText(Double.toString(new DatosGraficar().getValor2()));
                        vs1.setText(Double.toString(new DatosGraficar().getValor3()));
                        vd1.setText(Double.toString(new DatosGraficar().getValor4()));
                        }
                    
                    if (cont == 2)
                        {
                        jlnm2.setText(new DatosGraficar().getNombre());
                        jlci2.setText(Double.toString(new DatosGraficar().getValor1()));
                        ca2.setText(Double.toString(new DatosGraficar().getValor2()));
                        vs2.setText(Double.toString(new DatosGraficar().getValor3()));
                        vd2.setText(Double.toString(new DatosGraficar().getValor4()));
                        }
                        cont++;
                }
        }
        else
            
        if(eve == 3)
        {
        jlnm1.setText(new DatosGraficar().getNombre());
        jlci1.setText(Double.toString(new DatosGraficar().getValor1()));
        ca1.setText(Double.toString(new DatosGraficar().getValor2()));
        vs1.setText(Double.toString(new DatosGraficar().getValor3()));
        vd1.setText(Double.toString(new DatosGraficar().getValor4()));
        }
        
        if(eve == 4)
        {
        jlnm1.setText(new DatosGraficar().getNombre());
        jlci1.setText(Double.toString(new DatosGraficar().getValor1()));
        ca1.setText(Double.toString(new DatosGraficar().getValor2()));
        vs1.setText(Double.toString(new DatosGraficar().getValor3()));
        vd1.setText(Double.toString(new DatosGraficar().getValor4()));
        }
        
        if(eve == 5)
        {
        jlnm1.setText(new DatosGraficar().getNombre());
        jlci1.setText(Double.toString(new DatosGraficar().getValor1()));
        ca1.setText(Double.toString(new DatosGraficar().getValor2()));
        vs1.setText(Double.toString(new DatosGraficar().getValor3()));
        vd1.setText(Double.toString(new DatosGraficar().getValor4()));
        }
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectosVAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectosVAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectosVAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectosVAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectosVAN().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReg;
    private javax.swing.JLabel ca1;
    private javax.swing.JLabel ca2;
    private javax.swing.JLabel ca3;
    private javax.swing.JLabel ca4;
    private javax.swing.JLabel ca5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jlci1;
    private javax.swing.JLabel jlci2;
    private javax.swing.JLabel jlci3;
    private javax.swing.JLabel jlci4;
    private javax.swing.JLabel jlci5;
    public static javax.swing.JLabel jlnm1;
    private javax.swing.JLabel jlnm10;
    private javax.swing.JLabel jlnm2;
    private javax.swing.JLabel jlnm3;
    private javax.swing.JLabel jlnm4;
    private javax.swing.JLabel jlnm5;
    private javax.swing.JLabel jlnm6;
    private javax.swing.JLabel jlnm7;
    private javax.swing.JLabel jlnm8;
    private javax.swing.JLabel jlnm9;
    private javax.swing.JLabel mejor;
    private javax.swing.JLabel resp1;
    private javax.swing.JLabel resp2;
    private javax.swing.JLabel resp3;
    private javax.swing.JLabel resp4;
    private javax.swing.JLabel resp5;
    private javax.swing.JLabel vd1;
    private javax.swing.JLabel vd2;
    private javax.swing.JLabel vd3;
    private javax.swing.JLabel vd4;
    private javax.swing.JLabel vd5;
    private javax.swing.JLabel vs1;
    private javax.swing.JLabel vs2;
    private javax.swing.JLabel vs3;
    private javax.swing.JLabel vs4;
    private javax.swing.JLabel vs5;
    // End of variables declaration//GEN-END:variables
}
