package Formularios;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class TIR extends javax.swing.JFrame {


    public TIR() {
        initComponents();
        btnReg.setOpaque(false);
        btnReg.setContentAreaFilled(false);
        btnReg.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboEventos = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnComenzar = new javax.swing.JButton();
        btnReg = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCantidadd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(360, 270));
        setMinimumSize(new java.awt.Dimension(360, 270));
        setPreferredSize(new java.awt.Dimension(360, 270));
        setResizable(false);
        getContentPane().setLayout(null);

        cboEventos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        getContentPane().add(cboEventos);
        cboEventos.setBounds(30, 80, 70, 30);

        jLabel2.setText("Eventos:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 100, 20);

        btnComenzar.setText("Comenzar");
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComenzar);
        btnComenzar.setBounds(250, 80, 90, 30);

        btnReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon1.png"))); // NOI18N
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        getContentPane().add(btnReg);
        btnReg.setBounds(280, 180, 50, 40);

        jLabel3.setText("TIR:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 190, 70, 20);

        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblResultado.setText("TIR");
        getContentPane().add(lblResultado);
        lblResultado.setBounds(110, 190, 70, 20);

        jLabel5.setText("Deseado:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 60, 100, 20);
        getContentPane().add(txtCantidadd);
        txtCantidadd.setBounds(120, 80, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo15.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        int eventos =Integer.parseInt(cboEventos.getSelectedItem().toString());
        double cantidadd = Double.parseDouble(txtCantidadd.getText().toString());
        double result1 = 0, i = 1;
        
        double Dialogcantidad[] = new double [1000];
        
        for(int j=1; j<=eventos; j++)
        {
            JTextField  cantidad1 = new JTextField();

            Object[] mensaje =  {
                "Cantidad: ", cantidad1
            };
            int Opcion = JOptionPane.showConfirmDialog(null, mensaje,"Ingerese Cantidad: ", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
            if(Opcion==JOptionPane.OK_OPTION) // si el usiario presiona aceptar
            {
                Dialogcantidad[j] = Integer.parseInt(cantidad1.getText());
            }
        }
        
        //Comparación a puro WHILE
        while (result1 != cantidadd)
        {
            result1 = 0;
            double tasa = i/10000;
            for(int j=1; j<=eventos; j++)
                {
                    result1 += Dialogcantidad[j] / (Math.pow((1+tasa), j));
                }
            i++;
            if ((int)result1 == cantidadd)
            {
                JOptionPane.showMessageDialog(null, "TIR es: " + tasa);
                lblResultado.setText(Double.toString(tasa));
                return;
            }
        }
    }//GEN-LAST:event_btnComenzarActionPerformed

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TIR().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnReg;
    private javax.swing.JComboBox cboEventos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblResultado;
    public static javax.swing.JTextField txtCantidadd;
    // End of variables declaration//GEN-END:variables
}
