package Formularios;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class VAN extends javax.swing.JFrame {

    public VAN() {
        initComponents();
        btnReg.setOpaque(false);
        btnReg.setContentAreaFilled(false);
        btnReg.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnComenzar = new javax.swing.JButton();
        btnReg = new javax.swing.JButton();
        cboEventos = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtTMAR = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(360, 270));
        setMinimumSize(new java.awt.Dimension(360, 270));
        setPreferredSize(new java.awt.Dimension(360, 270));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("TMAR:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 120, 120, 20);

        btnComenzar.setText("Comenzar");
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComenzar);
        btnComenzar.setBounds(210, 90, 110, 30);

        btnReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon1.png"))); // NOI18N
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        getContentPane().add(btnReg);
        btnReg.setBounds(270, 150, 50, 40);

        cboEventos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        getContentPane().add(cboEventos);
        cboEventos.setBounds(20, 90, 100, 30);

        jLabel2.setText("Numero de eventos:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 140, 20);
        getContentPane().add(txtTMAR);
        txtTMAR.setBounds(20, 140, 100, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo13.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 360, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        int eventos =Integer.parseInt(cboEventos.getSelectedItem().toString());
        double interes = Double.parseDouble(txtTMAR.getText().toString());
        double tmar = interes/100;
        double pa, pf;

        //Varibales [2] del Vector
        String Dialognombre2[] = new String [1000];
        double Dialogci2[] = new double [1000];
        double Dialogca2[] = new double [1000];
        double Dialogvs2[] = new double [1000];
        double Dialogvida2[] = new double [1000];
        double result[] = new double [1000];
        
        //________________________________________________________
        
        for(int j=1; j<=eventos; j++) // for dependiendo del Num de Eventos q ingreso e usuario
        {           
            JTextField  nombre = new JTextField(); // textbox para cantidad
            JTextField  ci = new JTextField();
            JTextField  ca = new JTextField();
            JTextField  vs = new JTextField();
            JTextField  vida = new JTextField();
                   
            Object[] mensaje =  {    //objeto con los controles pa el inputdialog
                "Nombre: ", nombre, "Costo Inicial: ", ci, "Costo Anual", ca, "Valor de Salvamento: ", vs, "Vida: ", vida
            };
                int Opcion = JOptionPane.showConfirmDialog(null, mensaje,"Proyectos", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if(Opcion==JOptionPane.OK_OPTION) // si el usiario presiona aceptar
                {
                    String Dialognombre = (nombre.getText());
                    double Dialogci =Integer.parseInt(ci.getText());
                    double Dialogca=Integer.parseInt(ca.getText());
                    double Dialogvs=Integer.parseInt(vs.getText());
                    double Dialogvida=Integer.parseInt(vida.getText());
                    
                    //Vectorizando 
                        Dialognombre2[j] = Dialognombre;
                        Dialogci2[j]=Dialogci;
                        Dialogca2[j]=Dialogca;
                        Dialogvs2[j]=Dialogvs;
                        Dialogvida2[j]=Dialogvida;
                        
                        pa = Dialogca *((Math.pow((1+tmar), Dialogvida)-1) / (tmar * (Math.pow((1+tmar), Dialogvida))));
                        pf = Dialogvs / (Math.pow((1+tmar), Dialogvida));
                        result[j] = 0 - Dialogci - pa + pf;
                        JOptionPane.showMessageDialog(null, "El resultado es: "+ result[j]);
                        
                        /*Globalizacion
                        DatosGraficar global = new DatosGraficar();
                        global.setEvento(eventos);
                        global.setNombre(Dialognombre2[j]);
                        global.setValores(Dialogci2[j], Dialogca2[j], Dialogvs2[j], Dialogvida2[j]);
                        ________________________________________________________*/
                         
                }
        }
        ProyectosVAN formv = new ProyectosVAN(Dialognombre2, Dialogci2, Dialogca2, Dialogvs2, Dialogvida2, eventos);
        formv.setVisible(true);
    }//GEN-LAST:event_btnComenzarActionPerformed

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAN().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnReg;
    private javax.swing.JComboBox cboEventos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JTextField txtTMAR;
    // End of variables declaration//GEN-END:variables
}
